import test from 'node:test';
import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium, expect } from '@playwright/test';

// Emulate browser grants to verify UI gesture ordering and capture lifecycle.
// Native pointer lock still depends on the host browser granting the request.
for (const legacy of [false, true]) {
  test(`mouse capture: ${legacy ? 'legacy events' : 'promise API'}, narrow hybrid screen and retry`, { timeout: 45000 }, async () => {
    const browser = await chromium.launch({ channel: 'chromium', args: process.platform === 'darwin' ? ['--use-angle=metal'] : [] });
    try {
      const context = await browser.newContext({ viewport: { width: 640, height: 720 }, hasTouch: true });
      await context.addInitScript(({ legacy }) => {
        window.captureCalls = [];
        window.denyCapture = false;
        let locked = null;
        Object.defineProperty(document, 'pointerLockElement', { configurable: true, get: () => locked });
        document.exitPointerLock = () => { locked = null; document.dispatchEvent(new Event('pointerlockchange')); };
        Element.prototype.requestPointerLock = function () {
          window.captureCalls.push({ type: 'pointer', focused: document.activeElement === this });
          const fail = window.denyCapture;
          const complete = () => {
            if (fail) document.dispatchEvent(new Event('pointerlockerror'));
            else { locked = this; document.dispatchEvent(new Event('pointerlockchange')); }
          };
          if (legacy) { queueMicrotask(complete); return; }
          return Promise.resolve().then(() => { complete(); if (fail) throw new DOMException('Denied', 'NotAllowedError'); });
        };
        Element.prototype.requestFullscreen = function () {
          window.captureCalls.push({ type: 'fullscreen' });
          return Promise.reject(new DOMException('Test in-tab fallback', 'NotAllowedError'));
        };
      }, { legacy });
      const page = await context.newPage();
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      await page.goto(pathToFileURL(resolve('public/mario.html')).href);
      const canvas = page.locator('.world-canvas canvas');
      await page.getByRole('button', { name: 'Let’s play' }).click();
      await expect(canvas).toHaveAttribute('data-mouse-locked', 'true');
      assert.deepEqual(await page.evaluate(() => window.captureCalls.slice(0, 2)), [{ type: 'pointer', focused: true }, { type: 'fullscreen' }]);
      // Simulate the native unlock event generated by Escape.
      await page.evaluate(() => document.exitPointerLock());
      await expect(page.getByRole('heading', { name: 'Take a breather.' })).toBeVisible();
      await page.evaluate(() => { window.denyCapture = true; });
      await page.getByRole('button', { name: 'Keep playing' }).click();
      await expect(page.getByRole('button', { name: 'Pause game' })).toBeVisible();
      await expect(canvas).toHaveAttribute('data-mouse-locked', 'false');
      await page.evaluate(() => { window.denyCapture = false; });
      await canvas.click({ position: { x: 300, y: 300 } });
      await expect(canvas).toHaveAttribute('data-mouse-locked', 'true');
      await page.getByRole('button', { name: 'Pause game' }).click();
      const requests = await page.evaluate(() => window.captureCalls.filter(x => x.type === 'pointer').length);
      await page.getByRole('button', { name: 'Keep playing' }).tap();
      assert.equal(await page.evaluate(() => window.captureCalls.filter(x => x.type === 'pointer').length), requests, 'Touch Resume must not capture a mouse');
      assert.deepEqual(errors, []);
    } finally { await browser.close(); }
  });
}
