export const styles = `
.mario-bit{--top:16px;--bottom:40px;--left:16px;--right:16px;color:#fffbea;font:16px/1.4 system-ui,sans-serif;pointer-events:none;overflow:hidden;user-select:none;-webkit-user-select:none}
.mario-bit *{box-sizing:border-box}.mario-bit [hidden]{display:none!important}
.mario-bit button{font:700 14px system-ui;border:1px solid #ffffff40;color:inherit;background:#123736e8;border-radius:14px;min-height:44px;padding:10px 14px;cursor:pointer;pointer-events:auto;touch-action:none}
.mario-bit button:focus-visible{outline:3px solid #ffcc32;outline-offset:3px}.mario-bit button:disabled{opacity:.65;cursor:default}
.mario-bit header{position:absolute;top:var(--top);left:var(--left);right:var(--right);display:flex;align-items:center;justify-content:space-between;gap:8px;z-index:3;text-shadow:0 1px 5px #123736}
.mario-bit header b{font-size:20px;line-height:1.1}.mario-bit header small{display:block;font-size:11px;letter-spacing:2px;margin-top:4px}.mario-bit header>div{display:flex;gap:6px}
.mario-bit .panel,.mario-bit .help{position:absolute;left:50%;top:48%;transform:translate(-50%,-50%);width:min(88%,420px);max-height:70%;overflow:auto;background:#123736ed;border:1px solid #fff3;border-radius:24px;padding:26px;box-shadow:0 16px 60px #12373650;pointer-events:auto}
.mario-bit .panel small{color:#ffcc32;letter-spacing:3px;font-weight:700}.mario-bit h1{font-size:clamp(32px,9vw,50px);line-height:1.05;margin:18px 0}.mario-bit h1 span{display:block;font-size:16px;letter-spacing:3px;margin-top:10px}.mario-bit p{color:#e0ebe0;margin:16px 0 22px}.mario-bit .primary{background:#f34f3c;font-size:17px;width:100%;min-height:54px}.mario-bit [data-action=restart]{width:100%;margin-top:8px}
.mario-bit .help{z-index:5;max-height:72%;padding:22px}.mario-bit h2{margin-top:0}.mario-bit ul{padding-left:22px}.mario-bit li{margin:9px 0}
.mario-bit .hud{position:absolute;top:calc(var(--top) + 65px);left:var(--left);right:var(--right);display:flex;justify-content:space-around;gap:8px;background:#123736dc;padding:10px;border-radius:14px;font-weight:700;font-size:14px}
.mario-bit .progress{position:absolute;top:calc(var(--top) + 115px);left:var(--left);right:var(--right);height:4px;background:#12373670;border-radius:4px;overflow:hidden}.mario-bit .progress i{display:block;height:100%;background:#ffcc32}
.mario-bit .crosshair{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:22px;text-shadow:0 1px 3px #123736}
.mario-bit .controls{position:absolute;bottom:calc(var(--bottom) + 28px);left:var(--left);right:var(--right);display:flex;justify-content:space-between;align-items:center;gap:20px}
.mario-bit .joystick{width:112px;height:112px;border:2px solid #fff8;border-radius:50%;background:#12373670;position:relative;pointer-events:auto;touch-action:none;flex-shrink:0}.mario-bit .joystick i{position:absolute;left:30px;top:30px;width:48px;height:48px;border-radius:50%;background:#fff8;border:2px solid #fffc}.mario-bit .joystick span{position:absolute;bottom:-24px;width:100%;text-align:center;font-size:12px;font-weight:700;text-shadow:0 1px 4px #123736}
.mario-bit .actions{display:flex;align-items:center;gap:12px}.mario-bit [data-action=jump]{width:82px;height:82px;border-radius:50%;background:#f34f3cee}.mario-bit [data-action=run]{width:56px;height:56px;border-radius:50%;padding:0}.mario-bit [aria-pressed=true]{background:#b75b22}
.mario-bit .notice{position:absolute;bottom:calc(var(--bottom) + 190px);left:50%;transform:translateX(-50%);width:max-content;max-width:88%;background:#123736e8;border-radius:12px;padding:10px 16px;font-size:14px;text-align:center}.mario-bit .notice:empty{display:none}
@media(max-width:360px){.mario-bit header b{font-size:16px}.mario-bit header small{font-size:10px}.mario-bit header button{padding:8px 10px}.mario-bit .joystick{width:96px;height:96px}.mario-bit .joystick i{left:22px;top:22px}.mario-bit .actions{gap:8px}.mario-bit [data-action=jump]{width:72px;height:72px}}
@media(max-height:500px){.mario-bit .panel{top:53%;padding:18px;max-height:65%;width:380px}.mario-bit h1{font-size:30px;margin:6px 0}.mario-bit .panel p{margin:10px 0}.mario-bit .controls{bottom:var(--bottom)}.mario-bit .notice{bottom:calc(var(--bottom) + 122px)}.mario-bit .hud{left:25%;right:25%;top:var(--top)}.mario-bit .progress{top:calc(var(--top) + 51px);left:25%;right:25%}}
`;
